import{a as d,S as y,A as v}from"./assets/vendor-DjtasW9M.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const L="https://events-store.b.goit.study/api",c={CATEGORIES:"/categories",EVENTS:"/events",LIMIT:8};d.defaults.baseURL=L;async function f(){return(await d.get(c.CATEGORIES)).data}async function u(n=1,e=""){return e==="all"||e===void 0?(await d.get(`${c.EVENTS}?page=${n}&limit=${c.LIMIT}`)).data:(await d.get(`${c.EVENTS}?page=${n}&limit=${c.LIMIT}&category=${e}`)).data}const o={categoriesListEl:document.querySelector(".js-event-category-list"),categoriesListOpenSvgBtn:document.querySelector(".icon-rotate"),categoriesListOpen:document.querySelector(".event-category-list"),eventsList:document.querySelector(".events-list"),firstCategoryButton:document.querySelector(".categories__btn"),showMoreBtn:document.querySelector(".show-more-btn"),loader:document.querySelector(".loader")};function E(n,e){const r=n%4,i=n-r;return r===0||e<i?"row-of-4":r===3?"row-last-3":r===2?"row-last-2":r===1?"row-last-1":""}function w(n){const e=[{_id:"all",name:"Всі події",tags:[]},...n],r=e.map(({_id:i,name:t,tags:s},a)=>`<li class="event-category-item ${E(e.length,a)}" data-category="${i}">
          <p class="event-category-title">${t}</p>
          <p class="event-category-tags">${s.map(m=>`#${m}, `).join(" ")}</p>
        </li>`).join("");o.categoriesListEl.innerHTML=r,o.firstCategoryButton&&o.firstCategoryButton.classList.add("categories__btn--active"),window.innerWidth<768&&!o.categoriesListEl.SimpleBar&&new y(o.categoriesListEl,{autoHide:!1})}o.categoriesListOpenSvgBtn.addEventListener("click",S);function S(n){o.categoriesListOpenSvgBtn.classList.toggle("icon-rotate-rotated"),o.categoriesListOpen.classList.toggle("is-hidden")}function g(n){const e=n.map(({_id:r,name:i,price:t,category:s,image:a})=>`<li class="event-item">
        <img
          src="${a}"
          alt="${i}"
          width="335"
          height="251"
        />
        <div class="event-info">
          <p class="event-title">${i}</p>
          <p class="event-text">${s.name}</p>
          <p class="event-price">від ${t.value} грн</p>
        </div>
        <button type="button" class="event-details-btn" data-event-id="${r}">Детальніше</button>
      </li>`).join("");o.eventsList.insertAdjacentHTML("beforeend",e)}let p=1,h="all";async function $(){try{const n=await f();w(n);const{events:e}=await u(p,h);g(e)}catch(n){console.log("error events list",n)}}async function C(n){const e=n.target.closest(".event-category-item");if(!e)return;const r=e.dataset.category;if(r==="all"){const{events:i}=await u();o.eventsList.innerHTML="",g(i)}else{const t=(await f()).find(({_id:l})=>l===r),{events:s}=await u(),a=s.filter(({category:{name:l}})=>l===t.name);o.eventsList.innerHTML="",g(a)}}function O(n){p+=1;const e=n.target;console.log(e)}document.addEventListener("DOMContentLoaded",$);o.categoriesListEl.addEventListener("click",C);o.showMoreBtn.addEventListener("click",O);new v(".accordion-container",{showMultiple:!1});
//# sourceMappingURL=index.js.map
